### GET ALL BLOGS
GET http://localhost:3000/api/blogs

### CREATE A NEW VALID BLOG
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "new author",
  "url": "example.com",
  "title": "testing post request"
}

### CREATE A NEW INVALID BLOG
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "new author",
  "url": "example.com"
}

### UPDATE LIKES BY ID
PATCH http://localhost:3000/api/blogs/1

### DELETE A BLOG BY ID
DELETE http://localhost:3000/api/blogs/7

### GET ALL USERS
GET http://localhost:3000/api/users

### CREATE A USER
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "another",
  "username": "another@one.com",
  "password": "12345"
}

# {
#   "name": "testUser",
#   "username": "test",
#   "password": "12345"
# }

### CHANGE USERNAME
PUT http://localhost:3000/api/users/another13413
Content-Type: application/json

{
  "username": "another12"
}
