### GET ALL BLOGS
GET http://localhost:3000/api/blogs

### CREATE A NEW VALID BLOG
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "new author",
  "url": "example.com",
  "title": "testing post request"
}

### CREATE A NEW INVALID BLOG
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "author": "new author",
  "url": "example.com"
}

### UPDATE LIKES BY ID
PATCH http://localhost:3000/api/blogs/1

### DELETE A BLOG BY ID
DELETE http://localhost:3000/api/blogs/7
